name: coffee_app
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.10.7


dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  carousel_slider: ^5.1.2

  
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^6.0.0


flutter:
  assets:
    - assets/images/logo.png
    - assets/images/loading_background.png
    - assets/images/logo_horizontal_dark.png
    - assets/images/logo_horizontal_light.png
    - assets/icons/search.png 
    - assets/icons/cart.png
    - assets/icons/favorites.png
    - assets/icons/profile.png
    - assets/icons/home.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500

  uses-material-design: true
